name: "Nix cache post"
description: "Cache nix build post"
runs:
  using: "composite"
  steps:
    - name: Move nix store
      shell: bash
      run: |
        mkdir -p ~/nix ~/nix/var/nix/db/
        mv -f /nix/store ~/nix/store
        sudo mv -f /nix/var/nix/db/db.sqlite ~/nix/var/nix/db/db.sqlite
