resolver: lts-22.34

packages:
  - .

extra-deps:
  - base16-bytestring-1.0.2.0
  - freer-simple-1.2.1.2
  - generics-sop-0.5.1.4
  - github-0.29
  - http-link-header-1.2.1
  - open-union-0.4.0.0
  - th-abstraction-0.7.0.0
  - type-fun-0.1.3
  - typerep-map-0.6.0.0

# Required for freer-simple and typerep-map
allow-newer: true

nix:
#  packages: [pkg-config yq zlib]
  shell-file: ./nix/shell.nix
  pure: false
