resolver: lts-18.18

extra-deps:
  - open-union-0.4.0.0
  - type-fun-0.1.3
  - github-0.26
  - base16-bytestring-0.1.1.7
  - http-link-header-1.0.3.1

apply-ghc-options: everything
rebuild-ghc-options: true

ghc-options:
  "$everything": -O2 -fexpose-all-unfoldings -fspecialise-aggressively
  "pandoc": -O2 -fno-expose-all-unfoldings -fno-specialise-aggressively
