["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/getkin/kin-openapi"]
  sumVersion = "v0.66.0"
  ["github.com/getkin/kin-openapi".fetch]
    type = "git"
    url = "https://github.com/getkin/kin-openapi"
    rev = "6b4444becdebac4ea5658cbe205bac8c27a7ec41"
    sha256 = "08njvg2v14k2p3l1fwrmgg21k0fkli2ajac4893j5zky7a72sbiq"

["github.com/ghodss/yaml"]
  sumVersion = "v1.0.0"
  ["github.com/ghodss/yaml".fetch]
    type = "git"
    url = "https://github.com/ghodss/yaml"
    rev = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7"
    sha256 = "0skwmimpy7hlh7pva2slpcplnm912rp3igs98xnqmn859kwa5v8g"

["github.com/go-openapi/jsonpointer"]
  sumVersion = "v0.19.5"
  ["github.com/go-openapi/jsonpointer".fetch]
    type = "git"
    url = "https://github.com/go-openapi/jsonpointer"
    rev = "2446e21cad36eee826e1c2380f0ff747074a2faa"
    sha256 = "0azic9nfwywlz4qxvacyi4g668fbbrkcyv15bag02yfcsi8szg5c"

["github.com/go-openapi/swag"]
  sumVersion = "v0.19.5"
  ["github.com/go-openapi/swag".fetch]
    type = "git"
    url = "https://github.com/go-openapi/swag"
    rev = "c3d0f7896d589f3babb99eea24bbc7de98108e72"
    sha256 = "1z34vqc5yz6rzvarrvlhkimxx33p74iaxb28l1mv716njvlsmjhg"

["github.com/gorilla/mux"]
  sumVersion = "v1.8.0"
  ["github.com/gorilla/mux".fetch]
    type = "git"
    url = "https://github.com/gorilla/mux"
    rev = "98cb6bf42e086f6af920b965c38cacc07402d51b"
    sha256 = "18f0q9qxgq1yh4ji07mqhiydfcwvi56z9d775v7dc7yckj33kpdk"

["github.com/kr/pretty"]
  sumVersion = "v0.1.0"
  ["github.com/kr/pretty".fetch]
    type = "git"
    url = "https://github.com/kr/pretty"
    rev = "73f6ac0b30a98e433b289500d779f50c1a6f0712"
    sha256 = "18m4pwg2abd0j9cn5v3k2ksk9ig4vlwxmlw9rrglanziv9l967qp"

["github.com/kr/pty"]
  sumVersion = "v1.1.1"
  ["github.com/kr/pty".fetch]
    type = "git"
    url = "https://github.com/kr/pty"
    rev = "282ce0e5322c82529687d609ee670fac7c7d917c"
    sha256 = "0383f0mb9kqjvncqrfpidsf8y6ns5zlrc91c6a74xpyxjwvzl2y6"

["github.com/kr/text"]
  sumVersion = "v0.1.0"
  ["github.com/kr/text".fetch]
    type = "git"
    url = "https://github.com/kr/text"
    rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f"
    sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1"

["github.com/mailru/easyjson"]
  sumVersion = "v0.0.0-20190626092158-b2ccc519800e"
  ["github.com/mailru/easyjson".fetch]
    type = "git"
    url = "https://github.com/mailru/easyjson"
    rev = "b2ccc519800e761ac8000b95e5d57c80a897ff9e"
    sha256 = "0q85h383mhbkcjm2vqm72bi8n2252fv3c56q3lclzb8n2crnjcdk"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/yuin/goldmark"]
  sumVersion = "v1.4.0"
  ["github.com/yuin/goldmark".fetch]
    type = "git"
    url = "https://github.com/yuin/goldmark"
    rev = "5588d92a56fe1642791cf4aa8e9eae8227cfeecd"
    sha256 = "0n3xhna2rnxixjy5d7gfvgjkhddppa8hpzd8i8b68yb2l016g3qk"

["gopkg.in/check.v1"]
  sumVersion = "v1.0.0-20190902080502-41f04d3bba15"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "41f04d3bba152ddec2103e299fed053415705330"
    sha256 = "0vfk9czmlxmp6wndq8k17rhnjxal764mxfhrccza7nwlia760pjy"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.3.0"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "0b1645d91e851e735d3e23330303ce81f70adbe3"
    sha256 = "1md0hlyd9s6myv3663i9l59y74n4xjazifmmyxn43g86fgkc5lzj"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20210107192922-496545a6307b"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "496545a6307b2a7d7a710fd516e5e16e8ab62dbc"
    sha256 = "06f4lnrp494wqaygv09dggr2dwf3z2bawqhnlnnwiamg5y787k4g"
