name: "Nix cache"
description: "Cache nix build"
inputs:
  key:
    description: "Caching key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache Nix
      id: cache-nix
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/nix/store
        key: ${{ inputs.key }}
    - name: Move nix store
      uses: ilyakooo0/github-composite-action-pre-post@1.0.0
      with:
        pre: |
          if [[ -d ~/nix/store ]]; then
            sudo mkdir -p /nix/store
            sudo mv -f ~/nix/store/* /nix/store/
          fi
        post: |
          mkdir -p ~/nix/store
          sudo mv -f /nix/store/* ~/nix/store/
