name: "Nix cache"
description: "Cache nix build"
inputs:
  key:
    description: "Caching key"
    required: true
  restore-keys:
    description: "Restore keys"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: make nix store writable
      shell: bash
      run: |
        sudo chown -R $USER /nix
    - name: Cache Nix
      id: cache-nix
      uses: actions/cache@v2.1.7
      with:
        path: |
          /nix
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
    # - name: Move nix store
    #   shell: bash
    #   run: |
    #     echo
    #     ls /nix/store
    #     if [[ -d "~/nix/store/" ]]; then
    #       echo
    #       ls ~/nix/store
    #       sudo mkdir -p /nix/store
    #       sudo mv -f ~/nix/store/* /nix/store/
    #     fi
    #     echo
    #     ls /nix/store
