name: "Nix cache"
description: "Cache nix build"
inputs:
  key:
    description: "Caching key"
    required: true
  restore-keys:
    description: "Restore keys"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cache Nix
      id: cache-nix
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/nix/store
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
    - name: Move nix store
      shell: bash
      run: |
        if [[ -d "~/nix/store/" ]]; then
          sudo mkdir -p /nix/store
          sudo mv -f ~/nix/store/* /nix/store/
        fi
