name: "Nix cache"
description: "Cache nix build"
inputs:
  key:
    description: "Caching key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache Nix
      id: cache-nix
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/nix
        key: ${{ inputs.key }}
    - name: Move nix store
      shell: bash
      env:
        CACHE_HIT: ${{ steps.cache-nix.outputs.cache-hit }}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo mkdir -p /nix
          sudo mv -f ~/nix/* /nix/
        fi
    - name: Move nix store post
      uses: ilyakooo0/github-composite-action-pre-post@1.0.0
      with:
        post: |
          mkdir -p ~/nix
          sudo mv -f /nix/* ~/nix/
