name: "Nix cache"
description: "Cache nix build"
inputs:
  key:
    description: "Caching key"
    required: true
  restore-keys:
    description: "Restore keys"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # - name: Install Nix
    #   uses: cachix/install-nix-action@v16
    #   with:
    #     extra_nix_config: |
    #       system-features = kvm
    #       trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    #       substituters = https://hydra.iohk.io https://cache.nixos.org/
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          system-features = kvm
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - name: Cache Nix
      id: cache-nix
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/nix/store/
          ~/nix/var/nix/profiles/
          ~/nix/var/nix/db/
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
    - name: make nix store writable
      shell: bash
      run: |
        ls ~
        echo
        if [[ -d ~/nix ]]; then
          echo "in"
          ls ~/nix
          sudo mv -f ~/nix/store/* /nix/store/
          sudo mv -f ~/nix/var/nix/profiles/* /nix/var/nix/profiles/
          sudo mv -f ~/nix/var/nix/db/* /nix/var/nix/db/
        fi
