name: "Common setup"
description: "Common setup steps"
inputs:
  key:
    description: "Caching key"
    required: true
  restore-keys:
    description: "Restore keys"
    required: false
runs:
  using: "composite"
  steps:
    - name: Cache Nix
      uses: ./.github/actions/nix_cache
      with:
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          system-features = kvm
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/

