name: "Common setup"
description: "Common setup steps"
inputs:
  cachixSigningKey:
    description: "Cachix signing key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          system-features = kvm
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/

    # - name: Login to Cachix
    #   uses: cachix/cachix-action@v10
    #   with:
    #     name: octopod
    #     signingKey: ${{ inputs.cachixSigningKey }}
