name: "Push Docker Images"
description: "Push Docker Images"
inputs:
  tag:
    description: "The docker image tag to push."
    required: true
  docker_username:
    description: "The Docker Hub username"
    required: true
  docker_password:
    description: "The Docker Hub password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Push Docker Images to DockerHub
      shell: bash
      run: |
        skopeo copy docker-archive:$(nix-build -A compaRESTGithubAction -j auto) docker://typeable/comparest-github-action:${{ inputs.tag }}
        skopeo copy docker-archive:$(nix-build -A compaRESTImage -j auto) docker://typeable/comparest:${{ inputs.tag }}
